#include <string.h>
#include <stdio.h>
#include <time.h>
#include <stdlib.h>
#include <sys/time.h>
#include "sgx_urts.h"
#include "Enclave_u.h" // Headers for untrusted part (autogenerated by edger8r)


# define MAX_PATH FILENAME_MAX
# define ENCLAVE_FILENAME "enclave.signed.so"


//# define DEBUGLOG 

// ocalls for printing string (C++ ocalls)
void ocall_print_error(const char *str){
    printf("%s",str);
}

void ocall_print_string(const char *str){
    printf("%s",str);
}

void ocall_println_string(const char *str){
    printf("%s",str);
}

void u_test_main(void)
{
      struct timeval start, end;

  gettimeofday(&start, NULL);

  for (int i = 0; i < 1000; i++)
    {
                printf("ok");

    }
                printf("ok\n");

  gettimeofday(&end, NULL);
    printf("%ld\n",start.tv_usec);
  printf("%ld\n",end.tv_usec);



    return 0;
}


// Application entry
int main(int argc, char *argv[]){


    printf("enclave run\n");

  sgx_enclave_id_t eid = 0;
    char token_path[MAX_PATH] = {'\0'};
    sgx_launch_token_t token = {0};
    sgx_status_t ret = SGX_ERROR_UNEXPECTED; // status flag for enclave calls
    int updated = 0;
    char *sql;
    // Initialize the enclave
    ret = sgx_create_enclave(ENCLAVE_FILENAME, SGX_DEBUG_FLAG, &token, &updated, &eid, NULL);
    if (ret != SGX_SUCCESS) {
        printf("Error: creating enclave\n" );
        return -1;
    }
    test_main(eid);



   
    sgx_destroy_enclave(eid);
    if (ret != SGX_SUCCESS) {
        printf("Error: destroying enclave\n");
        return -1;
    }

    return 0;
}
